### ISSUE TITLE
No phptop records found - although they exist!

### ISSUE THREAD

**Issue by j75** [bearstech/phptop#1]
Running `phptop -l ./error.log -t 80000` produces the message `No phptop records found.`

However in the **error.log** file there are records obviously added by **phptop** :
```
[Wed Oct 07 09:24:30.634403 2020] [php7:notice] [pid 19891:tid 140633495107328] [client 123.123.123.1:25655] phptop time:0.003 user:0.003 sys:0.000 mem:002M url:https://myserver/
[Wed Oct 07 09:24:30.727151 2020] [php7:notice] [pid 19891:tid 140633453143808] [client 123.123.123.1:25655] phptop time:0.004 user:0.000 sys:0.004 mem:002M url:https://myserver/
```
So I suspect the error lines are not correctly parsed! How could this be fixed?

**Comment by zerodeux** [comment]
I did check and those lines are correctly parsed.

Are you sure you're asking results within the default time window (5min) ? Otherwise use for instance "-t 3600" to analyse results from now an back to 1 hour ago.

**Comment by zerodeux** [comment]
Ops sorry I have parsing fixes in my local tree which where not pushed ... I'll commit that quickly.

**Comment by zerodeux** [comment]
I've pushed phptop 0.5.8 which sould fix your problem.

**Comment by j75** [comment]
Yes, I confirm - thank you!
