### ISSUE TITLE
Latest release breaks on Jessie (PHP 5.3)

### ISSUE THREAD

**Issue by lukhas** [bearstech/phptop#2]
The latest release is broken on PHP 5.3 with the following error in the logs:

```
[Tue Oct 20 10:46:35.576250 2020] [fcgid:warn] [pid 3906:tid 140319014196992] [client X.X.X.X:52266] mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '*' in /usr/share/phptop/phptop_hook.php on line 53
```

Line 53 is https://github.com/bearstech/phptop/blob/master/phptop_hook.php#L53.

Not sure if it has been broken for years and just recently noticed or if something else broke with the latest release (the server in question was running 0.5.6 before upgrading to 0.5.8).

**Comment by zerodeux** [comment]
Aww... https://www.php.net/manual/en/language.operators.arithmetic.php : "$a ** $b | Exponentiation | Result of raising $a to the $b'th power. Introduced in PHP 5.6."

The portable operator is pow().
