### ISSUE TITLE
phptop not found

### ISSUE THREAD

**Issue by Setsuneh** [bearstech/phptop#3]
Trying to install it on Debian 12 + PHP7.3, seems i forgot something 

`echo auto_prepend_file=/usr/share/phptop/phptop_hook.php >> /etc/php/7.3/cli/php.ini`
`service apache2 restart`

Thus when i launch it after restarting Apache2 

```
root@scw-vigilant-carson:/usr/share# phptop -s mem
-bash: phptop: command not found
```

Any idea ?

**Comment by zerodeux** [comment]
How did you install phptop ? With APT or with `git clone` ?

The `phptop` program should be in `/usr/bin/` and thus available via your `$PATH`.
